const genres = [
  { id: 1, genre: "Biography" },
  { id: 10402, genre: "Music" },
  { id: 10749, genre: "Romance" },
  { id: 10751, genre: "Family" },
  { id: 10752, genre: "War" },
  { id: 10763, genre: "News" },
  { id: 10764, genre: "Reality" },
  { id: 10767, genre: "Talk Show" },
  { id: 12, genre: "Adventure" },
  { id: 14, genre: "Fantasy" },
  { id: 16, genre: "Animation" },
  { id: 18, genre: "Drama" },
  { id: 2, genre: "Film Noir" },
  { id: 27, genre: "Horror" },
  { id: 28, genre: "Action" },
  { id: 3, genre: "Game Show" },
  { id: 35, genre: "Comedy" },
  { id: 36, genre: "History" },
  { id: 37, genre: "Western" },
  { id: 4, genre: "Musical" },
  { id: 5, genre: "Sport" },
  { id: 53, genre: "Thriller" },
  { id: 6, genre: "Short" },
  { id: 7, genre: "Adult" },
  { id: 80, genre: "Crime" },
  { id: 878, genre: "Science Fiction" },
  { id: 9648, genre: "Mystery" },
  { id: 99, genre: "Documentary" },
];
genres.sort((a, b) => a.genre.localeCompare(b.genre));
export default genres;
